# Generated by Django 3.2.11 on 2022-06-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Handyman',
            new_name='is_handyman',
        ),
    ]
