# Generated by Django 3.2.11 on 2022-07-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_is_handyman_user_is_handyman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Client',
            new_name='is_client',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_financemanager',
            field=models.BooleanField(default=False, help_text='Means user can login to financemanager portal'),
        ),
    ]
