# Generated by Django 3.2.11 on 2022-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20220711_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='User/profile/default.jpg', upload_to='User/profile/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Activated, Users profile is published', verbose_name='Active'),
        ),
    ]
