# Generated by Django 3.2.11 on 2022-07-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20220718_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_handyman',
            field=models.BooleanField(default=False, help_text='Means user can login to handyman portal'),
        ),
    ]
