# Generated by Django 3.2.11 on 2022-08-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_is_handyman'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Means user can login to manager portal'),
        ),
    ]
