# Generated by Django 3.2.11 on 2022-06-21 08:33

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handyman',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user')),
                ('user_type', models.CharField(choices=[('ELECTRICIAN', 'ELECTRICIAN'), ('PAINTERS', 'PAINTERS'), ('TRANSPORTERS', 'TRANSPORTERS')], default='ELECTRICIAN', max_length=250)),
            ],
            options={
                'verbose_name': 'Handyman',
                'verbose_name_plural': 'Handyman',
            },
            bases=('Users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HandymanProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.profile')),
                ('ClientService', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flights.ClientService')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handyman.handyman')),
            ],
            options={
                'verbose_name': 'Handyman Profile',
                'verbose_name_plural': 'Handyman Profiles',
            },
            bases=('Users.profile',),
        ),
        migrations.CreateModel(
            name='HandymanFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handyman.handyman')),
            ],
            options={
                'verbose_name': 'Handyman Feedback',
                'verbose_name_plural': 'Handyman Feedback',
            },
            bases=('Users.feedback',),
        ),
        migrations.CreateModel(
            name='CheckAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('ELECTRICIAN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handyman.handyman')),
            ],
        ),
    ]
