# Generated by Django 3.2.11 on 2022-06-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handyman',
            name='user_type',
            field=models.CharField(choices=[('ELECTRICIAN', 'ELECTRICIAN'), ('PAINTERS', 'PAINTERS'), ('TRANSPORTERS', 'TRANSPORTERS'), ('FUMIGANTS', 'FUMIGANTS')], default='ELECTRICIAN', max_length=250),
        ),
    ]
