# Generated by Django 3.2.11 on 2022-07-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0003_auto_20220709_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handymanprofile',
            name='Service',
        ),
    ]
