# Generated by Django 3.2 on 2022-07-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0004_remove_handymanprofile_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handyman',
            old_name='user_type',
            new_name='User_type',
        ),
        migrations.RenameField(
            model_name='handymanfeedback',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='handymanprofile',
            old_name='user',
            new_name='User',
        ),
    ]
