# Generated by Django 3.2.11 on 2022-07-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20220718_0938'),
        ('handyman', '0006_auto_20220718_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handymanprofile',
            name='ClientService',
        ),
        migrations.AddField(
            model_name='handymanprofile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.service'),
        ),
    ]
