# Generated by Django 3.2.11 on 2022-07-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='clientfeedback',
            options={'verbose_name': 'Client Feedback', 'verbose_name_plural': 'Client Feedback'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Client Profile', 'verbose_name_plural': 'Client Profile'},
        ),
    ]
