# Generated by Django 3.2.11 on 2022-07-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220709_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'client'},
        ),
        migrations.AlterModelOptions(
            name='clientfeedback',
            options={'verbose_name': 'client Feedback', 'verbose_name_plural': 'client Feedback'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'client Profile', 'verbose_name_plural': 'client Profile'},
        ),
    ]
