# Generated by Django 3.2.11 on 2022-08-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220711_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfeedback',
            options={'verbose_name': 'clientFeedback', 'verbose_name_plural': 'clientFeedback'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'clientProfile', 'verbose_name_plural': 'clientProfile'},
        ),
    ]
