# Generated by Django 3.2.11 on 2022-07-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20220709_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='clientservice',
            old_name='Client',
            new_name='client',
        ),
    ]
