# Generated by Django 3.2.11 on 2022-07-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0004_remove_handymanprofile_service'),
        ('client', '0003_auto_20220711_1118'),
        ('flights', '0004_auto_20220711_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='clientservice',
            name='handyman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handyman.handyman'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
