# Generated by Django 3.2.11 on 2022-08-01 07:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0007_auto_20220718_0938'),
        ('client', '0004_auto_20220801_0937'),
        ('Users', '0006_user_is_manager'),
        ('financemanager', '0003_auto_20220713_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user')),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
            },
            bases=('Users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='served',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.appointment')),
                ('Payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financemanager.payment')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('manager', models.ForeignKey(help_text='management officer', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
        ),
        migrations.CreateModel(
            name='managerProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.profile')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
            options={
                'verbose_name': 'manager Profile',
                'verbose_name_plural': 'managers Profile',
            },
            bases=('Users.profile',),
        ),
        migrations.CreateModel(
            name='managerFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.feedback')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
            options={
                'verbose_name': 'manager Feedback',
                'verbose_name_plural': 'manager Feedback',
            },
            bases=('Users.feedback',),
        ),
    ]
