# Generated by Django 3.2 on 2022-07-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financemanager', '0002_alter_payment_financemanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financemanagerfeedback',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='financemanagerprofile',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='payment',
            name='financemanager',
            field=models.ForeignKey(help_text='Financemanager', null=True, on_delete=django.db.models.deletion.CASCADE, to='financemanager.financemanager'),
        ),
    ]
